### ISSUE TITLE
How to fix Error "Failed to Download UnityDependencies!"

### ISSUE THREAD

**Issue by NelDaDude** [LavaGang/MelonLoader.Installer#13]
I'm trying to mod BTD6 and I did everything that I needed to do. I got MelonLoader, the Mod Helper, and .NET 6.0 but when I open the game it says "Failed to Downlaod UnityDependencies!". How do I fix it?
<img width="960" alt="{08EAE602-7338-450B-9BE1-DCB58EF44CA8}" src="https://github.com/LavaGang/MelonLoader.Installer/assets/145769035/f63dd98d-7cbc-4fc9-9bde-543e4d03ee6f">

**Comment by RinLovesYou** [comment]
This is the repository for the MelonLoader Installer, not MelonLoader. Open an issue [here](https://github.com/lavagang/melonloader) and upload a log.
