### ISSUE TITLE
it says that im missing a library

### ISSUE THREAD

**Issue by btd6modderthatneedshelp** [LavaGang/MelonLoader.Installer#16]
idk but it says that im missing the library
i have installed the dependencies so is there something im missing?

**Comment by btd6modderthatneedshelp** [comment]
it just says library is missing and its when i try to launch btd6

**Comment by rakosi2** [comment]
Closing since this sounds like an issue with MelonLoader and not with the installer.
Do make sure that you have [.Net 6.0 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.23-windows-x64-installer) installed
