### ISSUE TITLE
melonloader installer not loading

### ISSUE THREAD

**Issue by HZDWOODY** [LavaGang/MelonLoader.Installer#34]
I have tried installing melon loader but it keeps crashing after updating, and doesn't let me open it after the update is finished

**Comment by slxdy** [comment]
Can you try this bleeding-edge build?
https://github.com/LavaGang/MelonLoader.Installer/actions/runs/11954202395/artifacts/2218808656

Note that this is a temporary solution. You should reinstall to the latest version as soon as the patch is officially released

**Comment by HZDWOODY** [comment]
doesnt work does the same thing

**Comment by HZDWOODY** [comment]
no

**Comment by slxdy** [comment]
If you hover over the installer executable and look at the pop-up, what version number does it say?

**Comment by HZDWOODY** [comment]
no

**Comment by slxdy** [comment]
Can we switch over to the Discord support channel so I can help diagnose the issue further?
https://discord.gg/PuUCBZ3V

**Comment by HerpDerpinstine** [comment]
Can you please try the latest development nightly build?
https://nightly.link/LavaGang/MelonLoader.Installer/workflows/build/development/MelonLoader.Installer.zip
